
server:
  port: 8082
spring:
#  datasource:
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=FALSE
#    url: jdbc:mysql://localhost:3306/user?serverTimezone=GMT%2B8&amp;characterEncoding=utf-8&amp;useSSL=FALSE
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp